spring.application.name=project

spring.datasource.url=jdbc:mysql://localhost:3306/ENTER-YOUR-DATABASE-NAME
spring.datasource.username=ENTER-YOUR-USERNAME
spring.datasource.password=ENTER-YOUR-PASSWORD
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
